#!/usr/bin/env bash

if [ -z "GITLAB_URL"]; then
  echo "You must provide GITLAB_URL"
  exit 1
fi

if [ -z "GITLAB_TOKEN"]; then
  echo "You must provide GITLAB_TOKEN"
  exit 1
fi

exec broker --verbose --disableBodyVarsSubstitution --disableHeaderVarsSubstitution
