#!/usr/bin/env bash

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
  DEFAULT_K8S_SERVICE_ACCOUNT_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
fi

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/ca.crt ]; then
  export CA_FILE=${CA_FILE:-/var/run/secrets/kubernetes.io/serviceaccount/ca.crt}
fi

export K8S_SERVICE_ACCOUNT_TOKEN="${K8S_SERVICE_ACCOUNT_TOKEN:-$DEFAULT_K8S_SERVICE_ACCOUNT_TOKEN}"
export CLUSTER_ENDPOINT="${CLUSTER_ENDPOINT:-https://kubernetes.default}"

if [ -z "$K8S_SERVICE_ACCOUNT_TOKEN"]; then
  echo "You must provide K8S_SERVICE_ACCOUNT_TOKEN"
  exit 1
fi

exec broker --verbose
