name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-containers:
    runs-on:
      labels: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Build Base Image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: roadiehq/broker:base
          context: dockerfiles
          file: dockerfiles/plugins/base.Dockerfile
      - name: Build Kubernetes
        uses: docker/build-push-action@v4
        with:
          push: false
          file: dockerfiles/plugins/Dockerfile
          context: dockerfiles/plugins/kubernetes
          tags: roadiehq/broker:pr-${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-kubernetes
      - name: Build Sonarqube
        uses: docker/build-push-action@v4
        with:
          push: false
          file: dockerfiles/plugins/Dockerfile
          context: dockerfiles/plugins/sonarqube
          tags: roadiehq/broker:pr-${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-sonarqube
      - name: Build Jenkins
        uses: docker/build-push-action@v4
        with:
          push: false
          file: dockerfiles/plugins/Dockerfile
          context: dockerfiles/plugins/jenkins
          tags: roadiehq/broker:pr-${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-jenkins
