name: Push

on:
  push:
    branches:
      - main

jobs:
  build-containers:
    env:
      BROKER_VERSION: 4.217.4 # STOP: This version must match version in package.json file
    runs-on:
      labels: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: kubernetes
            context: dockerfiles/kubernetes
          - name: grafana
            context: dockerfiles/grafana
          - name: sonarqube
            context: dockerfiles/sonarqube
          - name: jenkins
            context: dockerfiles/jenkins
          - name: cost-insights
            context: dockerfiles/cost-insights
          - name: argocd
            context: dockerfiles/argocd
          - name: github-enterprise
            context: dockerfiles/github-enterprise
          - name: bitbucket-server
            context: dockerfiles/bitbucket-server

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Base Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: roadiehq/broker:base
          platforms: linux/amd64,linux/arm64
          context: dockerfiles
          file: dockerfiles/base.Dockerfile
      - name: Build ${{ matrix.service.name }}
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.service.context }}
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-${{ matrix.service.name }},roadiehq/broker:${{ matrix.service.name }}
          build-args: |
            "BROKER_VERSION=${{ env.BROKER_VERSION }}"