name: Push

on:
  push:
    branches:
      - main

jobs:
  build-containers:
    runs-on:
      labels: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Base Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: roadiehq/broker:base
          context: dockerfiles
          file: dockerfiles/base.Dockerfile
      - name: Build Kubernetes
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          context: dockerfiles/kubernetes
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-kubernetes,roadiehq/broker:kubernetes
      - name: Build Grafana
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          context: dockerfiles/grafana
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-grafana,roadiehq/broker:grafana
      - name: Build Sonarqube
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          context: dockerfiles/sonarqube
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-sonarqube,roadiehq/broker:sonarqube
      - name: Build Jenkins
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          context: dockerfiles/jenkins
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-jenkins,roadiehq/broker:jenkins
      - name: Build Cost Insights
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          context: dockerfiles/cost-insights
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-cost-insights,roadiehq/broker:cost-insights
      - name: Build ArgoCD
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          context: dockerfiles/argocd
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-argocd,roadiehq/broker:argocd
      - name: Build GHES
        uses: docker/build-push-action@v4
        with:
          push: true
          file: dockerfiles/Dockerfile
          context: dockerfiles/github-enterprise
          tags: roadiehq/broker:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}-github-enterprise,roadiehq/broker:github-enterprise
